### ISSUE TITLE
Questions about running cell type prediction codes

### ISSUE THREAD

**Issue by HelloWorldLTY** [BioFM/OpenBioMed#18]
Hi, I tried to run the cell type prediction task based on CellLM, but got multiple errors.

If I used fixed version, it reports:

07/27/2023 02:22:35 - INFO - __main__ - 3160584 - ========Epoch 1========
  0%|                                                                                                                                                     | 0/15287 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tasks/cell_task/ctc.py", line 179, in <module>
    main(args, config)
  File "tasks/cell_task/ctc.py", line 158, in main
    train_ctc(train_loader, val_loader, model, device, args)
  File "tasks/cell_task/ctc.py", line 75, in train_ctc
    logits = model(cell)
  File "/gpfs/gibbs/project/zhao/tl688/conda_envs/OpenBioMed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gpfs/gibbs/pi/zhao/tl688/OpenBioMed/open_biomed/models/ctc_model.py", line 26, in forward
    h = self.encoder(data, return_encodings=True)
  File "/gpfs/gibbs/project/zhao/tl688/conda_envs/OpenBioMed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gpfs/gibbs/pi/zhao/tl688/OpenBioMed/open_biomed/models/cell_encoder/performer_celllm.py", line 794, in forward
    pos = torch.tensor(range(input_seq.shape[0]))[input_seq > 0].to(x.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

If I use new version, it reports:

Traceback (most recent call last):
  File "tasks/cell_task/ctc.py", line 179, in <module>
    main(args, config)
  File "tasks/cell_task/ctc.py", line 150, in main
    model = CTCModel(config["network"], dataset.num_classes)
  File "/gpfs/gibbs/pi/zhao/tl688/OpenBioMed/open_biomed/models/ctc_model.py", line 12, in __init__
    ckpt = ckpt[config["structure"]["param_key"]]
KeyError: 'model_state_dict'

Could you please help me debug it? Thanks a lot.

**Comment by HelloWorldLTY** [comment]
Hi, I think I have two questions in total. It also implies that I should use the fixed version, is it correct? Thanks a lot.

**Comment by toycatI** [comment]
Yes, the new version has some compatibility issues. You can use the fixed version for now. The fixed version is an earlier version of CellLM, and later on, we will release a new checkpoint that has been trained better.

**Comment by HelloWorldLTY** [comment]
Hi, sorry to disturb you again. Now I meet new problem: 

I intend to try new datasets, but I received this error:

/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [222,0,0], thread: [24,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [222,0,0], thread: [25,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [222,0,0], thread: [26,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [222,0,0], thread: [27,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [222,0,0], thread: [28,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [222,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [222,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [222,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
  0%|                                                                                                                                                      | 0/2485 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tasks/cell_task/ctc.py", line 179, in <module>
    main(args, config)
  File "tasks/cell_task/ctc.py", line 158, in main
    train_ctc(train_loader, val_loader, model, device, args)
  File "tasks/cell_task/ctc.py", line 75, in train_ctc
    logits = model(cell)
  File "/gpfs/gibbs/project/zhao/tl688/conda_envs/OpenBioMed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gpfs/gibbs/pi/zhao/tl688/OpenBioMed/open_biomed/models/ctc_model.py", line 26, in forward
    h = self.encoder(data, return_encodings=True)
  File "/gpfs/gibbs/project/zhao/tl688/conda_envs/OpenBioMed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gpfs/gibbs/pi/zhao/tl688/OpenBioMed/open_biomed/models/cell_encoder/performer_celllm.py", line 833, in forward
    x = self.performer(x, pos_emb = layer_pos_emb, output_attentions = output_attentions, mask = mask, **kwargs)
  File "/gpfs/gibbs/project/zhao/tl688/conda_envs/OpenBioMed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gpfs/gibbs/pi/zhao/tl688/OpenBioMed/open_biomed/models/cell_encoder/performer_celllm.py", line 710, in forward
    self.check_redraw_projections()
  File "/gpfs/gibbs/pi/zhao/tl688/OpenBioMed/open_biomed/models/cell_encoder/performer_celllm.py", line 696, in check_redraw_projections
    if exists(self.feature_redraw_interval) and self.calls_since_last_redraw >= self.feature_redraw_interval:
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


which comes from the embedding process.

It seems that in the example dataset, it contains -1 in the raw expresison space, which is not common.
<img width="937" alt="image" src="https://github.com/BioFM/OpenBioMed/assets/43333475/5b33cdd6-6934-463c-9df9-9f7c56d5afcd">

May I know how to test this model based on our own dataset? Thanks a lot.

**Comment by toycatI** [comment]
I'm sorry, but I haven't encountered this bug before. In the example dataset, -1 represents missing data. However, in our data processing, we don't distinguish between -1 and 0. Perhaps your dataset has some other format differences compared to the one we provided?

**Comment by toycatI** [comment]
> I'm sorry, but I haven't encountered this bug before. In the example dataset, -1 represents missing data. However, in our data processing, we don't distinguish between -1 and 0. Perhaps your dataset has some other format differences compared to the one we provided?

Maybe you can try processing the new data into the same format as the sample data.

**Comment by HelloWorldLTY** [comment]
The last bug I found here is from F1 score calculation.

Traceback (most recent call last):
  File "tasks/cell_task/ctc.py", line 189, in <module>
    main(args, config)
  File "tasks/cell_task/ctc.py", line 163, in main
    train_ctc(train_loader, val_loader, model, device, args)
  File "tasks/cell_task/ctc.py", line 103, in train_ctc
    results = val_ctc(val_loader, model, device, args)
  File "tasks/cell_task/ctc.py", line 135, in val_ctc
    "F1 Score": f1_score(all_preds, all_y),
  File "/gpfs/gibbs/project/zhao/tl688/conda_envs/OpenBioMed/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/gpfs/gibbs/project/zhao/tl688/conda_envs/OpenBioMed/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1238, in f1_score
    return fbeta_score(
  File "/gpfs/gibbs/project/zhao/tl688/conda_envs/OpenBioMed/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 184, in wrapper
    return func(*args, **kwargs)
  File "/gpfs/gibbs/project/zhao/tl688/conda_envs/OpenBioMed/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1411, in fbeta_score
    _, _, f, _ = precision_recall_fscore_support(
  File "/gpfs/gibbs/project/zhao/tl688/conda_envs/OpenBioMed/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 184, in wrapper
    return func(*args, **kwargs)
  File "/gpfs/gibbs/project/zhao/tl688/conda_envs/OpenBioMed/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1721, in precision_recall_fscore_support
    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
  File "/gpfs/gibbs/project/zhao/tl688/conda_envs/OpenBioMed/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1516, in _check_set_wise_labels
    raise ValueError(
ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

I think you can use weighted version if you want. Thanks a lot.

**Comment by toycat-I** [comment]
Hi! I recently checked the previous checkpoint and found that it doesn't match the current code, which is causing the model's performance to be subpar. We have uploaded a correct version of the checkpoint. Please use the new version if needed. I hope this will help you~

**Comment by toycat-I** [comment]
> Hi, I think I have two questions in total. It also implies that I should use the fixed version, is it correct? Thanks a lot.
@HelloWorldLTY 
Hi! I recently checked the previous checkpoint and found that it doesn't match the current code, which is causing the model's performance to be subpar. We have uploaded a correct version of the checkpoint. Please use the new version if needed. I hope this will help you~

**Comment by HelloWorldLTY** [comment]
Thanks a lot, I marked it.
