### ISSUE TITLE
about cuda version

### ISSUE THREAD

**Issue by qq7987590** [BioFM/OpenBioMed#8]
Hi, I am trying to deploy this project, I encountered the following error:
```
(OpenBioMed) root@iv-ycdgpn6dke7grboy6e0h:~/OpenBioMed/open_biomed# bash scripts/dti/train_baseline_regression.sh

/root/micromamba/envs/OpenBioMed/lib/python3.8/site-packages/torch_geometric/typing.py:31: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /root/micromamba/envs/OpenBioMed/lib/python3.8/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/root/micromamba/envs/OpenBioMed/lib/python3.8/site-packages/torch_geometric/typing.py:42: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /root/micromamba/envs/OpenBioMed/lib/python3.8/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Traceback (most recent call last):
  File "tasks/mol_task/dti.py", line 19, in <module>
    from datasets.dti_dataset import SUPPORTED_DTI_DATASETS
  File "/root/OpenBioMed/open_biomed/datasets/dti_dataset.py", line 17, in <module>
    from feat.drug_featurizer import SUPPORTED_DRUG_FEATURIZER, DrugMultiModalFeaturizer
  File "/root/OpenBioMed/open_biomed/feat/drug_featurizer.py", line 21, in <module>
    from torch_geometric.data import Data
  File "/root/micromamba/envs/OpenBioMed/lib/python3.8/site-packages/torch_geometric/__init__.py", line 1, in <module>
    import torch_geometric.utils
  File "/root/micromamba/envs/OpenBioMed/lib/python3.8/site-packages/torch_geometric/utils/__init__.py", line 8, in <module>
    from .dropout import dropout_adj, dropout_node, dropout_edge, dropout_path
  File "/root/micromamba/envs/OpenBioMed/lib/python3.8/site-packages/torch_geometric/utils/dropout.py", line 6, in <module>
    import torch_cluster  # noqa
  File "/root/micromamba/envs/OpenBioMed/lib/python3.8/site-packages/torch_cluster/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/root/micromamba/envs/OpenBioMed/lib/python3.8/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/root/micromamba/envs/OpenBioMed/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/micromamba/envs/OpenBioMed/lib/python3.8/site-packages/torch_cluster/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
```

It seems to be an issue with the CUDA version.
May I know which CUDA version you are using?
If possible, please also let me know the versions of PyTorch and other necessary dependencies. Thank you.

**Comment by BioFM** [comment]
Hi，thanks for your interest in OpenBioMed.
The CUDA version we used is 11.4, you can install PyTorch and other necessary dependencies use the following command. Other versions of CUDA like 11.3 work as well.
```shell
# linux
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 -c pytorch
```
We will supplement the dependencies of the environment in requirments.txt and build a docker image soon.
Best wishes！

**Comment by lxy-peter** [comment]
Hi there, this may be an issue related to the installation of extensions of PyTorch Geometric. You may have to manually download wheels from https://data.pyg.org/whl/ according to your version of PyTorch, then run `pip install <wheel_filename>` for each extension.

 We used
- torch_cluster-1.6.0-cp38-cp38-linux_x86_64.whl
- torch_scatter-2.0.9-cp38-cp38-linux_x86_64.whl
- torch_sparse-0.6.14-cp38-cp38-linux_x86_64.whl
- torch_spline_conv-1.2.1-cp38-cp38-linux_x86_64.whl

with PyTorch version 1.12.1+cu116 and PyTorch Geometric version 2.2.0.
